export const DISTRICTS_SEED = [
  { code: 'ABJ', nom: "District Autonome d'Abidjan" },
  { code: 'YAM', nom: 'District Autonome de Yamoussoukro' },
  { code: 'LAG', nom: 'District des Lagunes' },
  { code: 'COM', nom: 'District de la Comoé' },
  { code: 'LAC', nom: 'District des Lacs' },
  { code: 'MON', nom: 'District des Montagnes' },
  { code: 'SAS', nom: 'District du Sassandra-Marahoué' },
  { code: 'SAV', nom: 'District des Savanes' },
  { code: 'BAS', nom: 'District du Bas-Sassandra' },
  { code: 'DEN', nom: 'District du Denguélé' },
  { code: 'GOH', nom: 'District du Goh-Djiboua' },
  { code: 'VAB', nom: 'District de la Vallée du Bandama' },
  { code: 'WOR', nom: 'District des Woroba' },
  { code: 'ZAN', nom: 'District du Zanzan' },
];

export const REGIONS_SEED = [
  { code: 'ABJ-AUT', nom: 'Abidjan', districtCode: 'ABJ' },
  { code: 'YAM-AUT', nom: 'Yamoussoukro', districtCode: 'YAM' },
  { code: 'AGN', nom: 'Agnéby-Tiassa', districtCode: 'LAG' },
  { code: 'GRP', nom: 'Grands-Ponts', districtCode: 'LAG' },
  { code: 'LME', nom: 'La Mé', districtCode: 'LAG' },
  { code: 'IND', nom: 'Indénié-Djuablin', districtCode: 'COM' },
  { code: 'SUC', nom: 'Sud-Comoé', districtCode: 'COM' },
  { code: 'BEL', nom: 'Bélier', districtCode: 'LAC' },
  { code: 'IFF', nom: 'Iffou', districtCode: 'LAC' },
  { code: 'MOR', nom: 'Moronou', districtCode: 'LAC' },
  { code: 'NZI', nom: "N'Zi", districtCode: 'LAC' },
  { code: 'CAV', nom: 'Cavally', districtCode: 'MON' },
  { code: 'GUE', nom: 'Guémon', districtCode: 'MON' },
  { code: 'TON', nom: 'Tonkpi', districtCode: 'MON' },
  { code: 'HSA', nom: 'Haut-Sassandra', districtCode: 'SAS' },
  { code: 'MAR', nom: 'Marahoué', districtCode: 'SAS' },
  { code: 'BAG', nom: 'Bagoué', districtCode: 'SAV' },
  { code: 'POR', nom: 'Poro', districtCode: 'SAV' },
  { code: 'TCH', nom: 'Tchologo', districtCode: 'SAV' },
  { code: 'GBO', nom: 'Gbôklé', districtCode: 'BAS' },
  { code: 'NAW', nom: 'Nawa', districtCode: 'BAS' },
  { code: 'SPE', nom: 'San-Pédro', districtCode: 'BAS' },
  { code: 'FOL', nom: 'Folon', districtCode: 'DEN' },
  { code: 'KAB', nom: 'Kabadougou', districtCode: 'DEN' },
  { code: 'GOH-R', nom: 'Gôh', districtCode: 'GOH' },
  { code: 'LDJ', nom: 'Lôh-Djiboua', districtCode: 'GOH' },
  { code: 'GBE', nom: 'Gbêkê', districtCode: 'VAB' },
  { code: 'HAM', nom: 'Hambol', districtCode: 'VAB' },
  { code: 'BAF', nom: 'Bafing', districtCode: 'WOR' },
  { code: 'WOD', nom: 'Worodougou', districtCode: 'WOR' },
  { code: 'BER', nom: 'Béré', districtCode: 'WOR' },
  { code: 'BOK', nom: 'Bounkani', districtCode: 'ZAN' },
  { code: 'GON', nom: 'Gontougo', districtCode: 'ZAN' },
];

export const DEPARTEMENTS_SEED = [
  { code: 'ABJ', nom: 'Abidjan', regionCode: 'ABJ-AUT' },
  { code: 'YAM', nom: 'Yamoussoukro', regionCode: 'YAM-AUT' },
  { code: 'BKE', nom: 'Bouaké', regionCode: 'GBE' },
  { code: 'DAL', nom: 'Daloa', regionCode: 'HSA' },
  { code: 'KOR', nom: 'Korhogo', regionCode: 'POR' },
  { code: 'SPE', nom: 'San-Pédro', regionCode: 'SPE' },
  { code: 'MAN', nom: 'Man', regionCode: 'TON' },
  { code: 'DIV', nom: 'Divo', regionCode: 'LDJ' },
  { code: 'GAG', nom: 'Gagnoa', regionCode: 'GOH-R' },
  { code: 'ABE', nom: 'Abengourou', regionCode: 'IND' },
  { code: 'AGB', nom: 'Agboville', regionCode: 'AGN' },
  { code: 'ABO', nom: 'Aboisso', regionCode: 'SUC' },
  { code: 'BON', nom: 'Bondoukou', regionCode: 'GON' },
  { code: 'BOU', nom: 'Bouaflé', regionCode: 'MAR' },
  { code: 'DAB', nom: 'Dabou', regionCode: 'GRP' },
  { code: 'DIM', nom: 'Dimbokro', regionCode: 'NZI' },
  { code: 'FER', nom: 'Ferkessédougou', regionCode: 'TCH' },
  { code: 'ISS', nom: 'Issia', regionCode: 'HSA' },
  { code: 'KAT', nom: 'Katiola', regionCode: 'HAM' },
  { code: 'LAK', nom: 'Lakota', regionCode: 'LDJ' },
  { code: 'ODI', nom: 'Odienné', regionCode: 'KAB' },
  { code: 'SAS', nom: 'Sassandra', regionCode: 'GBO' },
  { code: 'SEG', nom: 'Séguéla', regionCode: 'WOD' },
  { code: 'SIN', nom: 'Sinfra', regionCode: 'MAR' },
  { code: 'SOU', nom: 'Soubré', regionCode: 'NAW' },
  { code: 'TAB', nom: 'Tabou', regionCode: 'SPE' },
  { code: 'TIA', nom: 'Tiassalé', regionCode: 'AGN' },
  { code: 'TOU', nom: 'Touba', regionCode: 'BAF' },
  { code: 'VAV', nom: 'Vavoua', regionCode: 'HSA' },
  { code: 'BIN', nom: 'Bingerville', regionCode: 'ABJ-AUT' },
];

export const COMMUNES_ABIDJAN_SEED = [
  { code: 'ABJ-ABO', nom: 'Abobo', departementCode: 'ABJ' },
  { code: 'ABJ-ADJ', nom: 'Adjamé', departementCode: 'ABJ' },
  { code: 'ABJ-ATT', nom: 'Attécoubé', departementCode: 'ABJ' },
  { code: 'ABJ-COC', nom: 'Cocody', departementCode: 'ABJ' },
  { code: 'ABJ-KOU', nom: 'Koumassi', departementCode: 'ABJ' },
  { code: 'ABJ-MAR', nom: 'Marcory', departementCode: 'ABJ' },
  { code: 'ABJ-PLA', nom: 'Plateau', departementCode: 'ABJ' },
  { code: 'ABJ-PBT', nom: 'Port-Bouët', departementCode: 'ABJ' },
  { code: 'ABJ-TRE', nom: 'Treichville', departementCode: 'ABJ' },
  { code: 'ABJ-YOP', nom: 'Yopougon', departementCode: 'ABJ' },
  { code: 'ABJ-ANY', nom: 'Anyama', departementCode: 'ABJ' },
  { code: 'ABJ-BIN', nom: 'Bingerville', departementCode: 'BIN' },
  { code: 'ABJ-SON', nom: 'Songon', departementCode: 'ABJ' },
];
