# Config interne du container frontend
server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Gzip
    gzip on;
    gzip_types text/plain text/css application/json application/javascript;

    # Cache des assets statiques (images, JS, CSS)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }


    # React Router — toutes les routes renvoient index.html
    location / {
        try_files $uri $uri/ /index.html;
    }
}
